# Generated by Django 5.0.1 on 2026-01-03 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_basic_salary_employee_break_time_hours_and_more'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_time_off', models.IntegerField(default=24, help_text='Annual paid leave days')),
                ('sick_time_off', models.IntegerField(default=7, help_text='Sick leave days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_allocation', to='employees.employee')),
            ],
            options={
                'db_table': 'leave_allocations',
            },
        ),
    ]
